# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import dju_common.fields.json
import tests.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JsonTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_1', dju_common.fields.json.JSONField(blank=True, default=None)),
                ('json_2', dju_common.fields.json.JSONField(blank=True, default=[])),
                ('json_3', dju_common.fields.json.JSONField(blank=True, default={})),
                ('json_4', dju_common.fields.json.JSONField(blank=True, default=tests.models.get_default)),
                ('json_5', dju_common.fields.json.JSONField(blank=True, default={b'a': 1})),
                ('json_6', dju_common.fields.json.JSONCharField(blank=True, default=None, max_length=255)),
                ('json_7', dju_common.fields.json.JSONCharField(blank=True, default=[], max_length=255)),
                ('json_8', dju_common.fields.json.JSONCharField(blank=True, default={}, max_length=255)),
                ('json_9', dju_common.fields.json.JSONCharField(blank=True, default=tests.models.get_default, max_length=255)),
                ('json_10', dju_common.fields.json.JSONCharField(blank=True, default={b'a': 1}, max_length=255)),
                ('json_11', dju_common.fields.json.JSONField(blank=True, default=None)),
                ('json_12', dju_common.fields.json.JSONField(blank=True, default=None, null=True)),
            ],
        ),
    ]
